#! /bin/sh

### Variables ###

export TERMINAL=alacritty
export BROWSER=zen-browser
export FILE_MANAGER=thunar

### Output ###
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --output HDMI-0 --primary
xrandr --output HDMI-0 --primary --output DP-0 --auto --left-of HDMI-0
bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10

### Rules/EnvVars ###
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

systemctl --user import-environment DISPLAY XAUTHORITY GTK_THEME VISUAL EDITOR XDG_CURRENT_DESKTOP
systemctl --user start bspwm-session.target
dbus-update-activation-environment --systemd GTK_THEME VISUAL EDITOR XDG_CURRENT_DESKTOP=bspwm

bspc rule -a Rofi state=floating center=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

### Visual ###
# Borders
bspc config border_width 1
bspc config window_gap 6
bspc config split_ratio 0.50

# Colors
# Focused
bspc config focused_border_color "#ffffff"
# Normal/Unfocused
bspc config normal_border_color "#595959"
# Urgent
bspc config urgent_border_color "#9b0000"

# Focus
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config pointer_modifier mod4

# Keep monitor on, it will be managed by the idle script.
xset s off dpms 0 0 0
xset -dpms s off

### Other ###
# Input settings (re-applied on hotplug by inputplug)
~/.config/bspwm/scripts/input.sh

# Cursor
xsetroot -cursor_name left_ptr

# idk
bspc config borderless_monocle true
bspc config gapless_monocle true

### Startup ###
# Inputplug for re-applying input settings on hotplug
pgrep -x inputplug >/dev/null || inputplug -c ~/.config/bspwm/scripts/input.sh &

# SXHKD for Keys
pgrep -x sxhkd >/dev/null || sxhkd &

# Feh for Wallpapers
feh --bg-fill ~/.config/Wallpaper.jpg &

# Polybar
~/.config/polybar/launch.sh &

# Idle
~/.config/bspwm/scripts/idle.sh &

# EasyEffects for Mic
easyeffects &
